name: CI

on:
  push: {}
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.owner.login != 'dylanahsmith'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        entry:
          - name: 'Minimum supported'
            ruby: 2.7
            gemfile: Gemfile.rails52
          - name: "Latest released versions"
            ruby: 3.2
            gemfile: Gemfile
          - name: "Rails main branch"
            ruby: 3.2
            gemfile: Gemfile.rails_head

    name: ${{ matrix.entry.name }}

    env:
      BUNDLE_GEMFILE: ${{ matrix.entry.gemfile }}

    steps:
    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get -y install libsqlite3-dev
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.entry.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
